### ISSUE TITLE
Great package

### ISSUE THREAD

**Issue by sullof** [bhagn/simple-shell#2]
The tool is fantastic but I could not make it working.
Is it possible to publish a gist with an example, like the source that you used for the demo at https://asciinema.org/a/coq21ef6bypf01ei1metfe3uo ?
Thanks so much

**Comment by bhagn** [comment]
I just added an example to the repo. You can refer to it to get started.

https://github.com/bhagn/simple-shell/tree/master/example

```
$ cd example
$ npm install
$ npm link
$ example
  _____  __   _   __  __ ___ _    ___
 | __\ \/ /  /_\ |  \/  | _ \ |  | __|
 | _| >  <  / _ \| |\/| |  _/ |__| _|
 |___/_/\_\/_/ \_\_|  |_|_| |____|___|

Copyright(c) 2017, JigiJigi | Version: 0.0.1

Type help to get started. To get help for any command just suffix the comand with help
example>
```

**Comment by sullof** [comment]
Thanks so much!
